#Makefile
CC = gcc
INCLUDE = /usr/lib
LIBS = 
OBJS = 

all: master sqr cube

master: 
	$(CC) -o master master.c $(CFLAGS) $(LIBS)
sqr:
	$(CC) -o sqr sqr.c $(CFLAGS) $(LIBS)
cube:
	$(CC) -o cube cube.c $(CFLAGS) $(LIBS)

clean:
	rm -f master sqr cube whole_num squares cubes core
